### ISSUE TITLE
darling-stub-gen fails on DVDPlayback

### ISSUE THREAD

**Issue by superbonaci** [darlinghq/darling#1027]
Following this guide on OS X 11.5.2, x86_64 architecture:

````
$ cd  ~
$ mkdir ~/bin
$ echo "export PATH=\"~/bin:\$PATH\"" >> ~/.bash_profile && source ~/.bash_profile
$ echo "export PATH=\"\$HOME/bin:\$PATH\"" >> ~/.zshenv && source ~/.zshenv
$ curl https://raw.githubusercontent.com/darlinghq/darling/master/tools/darling-stub-gen -o ~/bin/darling-stub-gen && chmod +x ~/bin/darling-stub-gen && curl https://github.com/darlinghq/class-dump/releases/download/mojave/class-dump -L -o ~/bin/class-dump && chmod +x ~/bin/class-dump
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100  9677  100  9677    0     0  28886      0 --:--:-- --:--:-- --:--:-- 28973
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100   618  100   618    0     0   1507      0 --:--:-- --:--:-- --:--:--  1511
100  857k  100  857k    0     0   798k      0  0:00:01  0:00:01 --:--:-- 1661k
````
````
$ darling-stub-gen /System/Library/Frameworks/DVDPlayback.framework/DVDPlayback DVDPlayback 
/Library/Developer/CommandLineTools/usr/bin/nm: error: /System/Library/Frameworks/DVDPlayback.framework/DVDPlayback: No such file or directory.
Traceback (most recent call last):
  File "/Users/Steve/bin/darling-stub-gen", line 130, in <module>
    c_func_out = subprocess.check_output(["nm", "-Ug", full_path])
  File "/usr/local/Cellar/python@3.9/3.9.6/Frameworks/Python.framework/Versions/3.9/lib/python3.9/subprocess.py", line 424, in check_output
    return run(*popenargs, stdout=PIPE, timeout=timeout, check=True,
  File "/usr/local/Cellar/python@3.9/3.9.6/Frameworks/Python.framework/Versions/3.9/lib/python3.9/subprocess.py", line 528, in run
    raise CalledProcessError(retcode, process.args,
subprocess.CalledProcessError: Command '['nm', '-Ug', '/System/Library/Frameworks/DVDPlayback.framework/DVDPlayback']' returned non-zero exit status 1.
````

**Comment by superbonaci** [comment]
Installed Xcode 21.5.1 and Command Line Tools 12.5.1. These are the contents of such folder:
````
% find /System/Library/Frameworks/DVDPlayback.framework
/System/Library/Frameworks/DVDPlayback.framework
/System/Library/Frameworks/DVDPlayback.framework/Resources
/System/Library/Frameworks/DVDPlayback.framework/Versions
/System/Library/Frameworks/DVDPlayback.framework/Versions/A
/System/Library/Frameworks/DVDPlayback.framework/Versions/A/_CodeSignature
/System/Library/Frameworks/DVDPlayback.framework/Versions/A/_CodeSignature/CodeResources
/System/Library/Frameworks/DVDPlayback.framework/Versions/A/Resources
/System/Library/Frameworks/DVDPlayback.framework/Versions/A/Resources/BridgeSupport
/System/Library/Frameworks/DVDPlayback.framework/Versions/A/Resources/BridgeSupport/DVDPlayback.bridgesupport
/System/Library/Frameworks/DVDPlayback.framework/Versions/A/Resources/BridgeSupport/DVDPlayback.arm64e.bridgesupport
/System/Library/Frameworks/DVDPlayback.framework/Versions/A/Resources/framework.sb
/System/Library/Frameworks/DVDPlayback.framework/Versions/A/Resources/Info.plist
/System/Library/Frameworks/DVDPlayback.framework/Versions/A/Resources/version.plist
/System/Library/Frameworks/DVDPlayback.framework/Versions/Current
````

**Comment by Inkmomot** [comment]
curtianly

**Comment by LubosD** [comment]
You can't generate stubs for files that are not present on your system.
