### ISSUE TITLE
Build Python 2.6/2.7

### ISSUE THREAD

**Issue by LubosD** [darlinghq/darling#119]
Build Python 2.6 and 2.7, as they are part of OS X.

- [x] 2.6
- [x] 2.7

**Comment by LubosD** [comment]
Need to define size of some symbols for Python math module:
````
[23:17:39][Step 1/1] /usr/bin/ld: warning: type and size of dynamic symbol `tanh@@DARWIN' are not defined
[23:17:39][Step 1/1] /usr/bin/ld: warning: type and size of dynamic symbol `ceil@@DARWIN' are not defined
[23:17:39][Step 1/1] /usr/bin/ld: warning: type and size of dynamic symbol `copysign@@DARWIN' are not defined
[23:17:39][Step 1/1] /usr/bin/ld: warning: type and size of dynamic symbol `cosh@@DARWIN' are not defined
[23:17:39][Step 1/1] /usr/bin/ld: warning: type and size of dynamic symbol `sinh@@DARWIN' are not defined
[23:17:39][Step 1/1] /usr/bin/ld: warning: type and size of dynamic symbol `fabs@@DARWIN' are not defined
[23:17:39][Step 1/1] /usr/bin/ld: warning: type and size of dynamic symbol `exp@@DARWIN' are not defined
````

**Comment by LubosD** [comment]
Crash in python 2.7:
````
#0  PyObject_InitVar (op=0x7ffff7f34150, tp=0x7ffff65a5360 <PyLong_Type>, size=-9223372036854775806) at /home/lubos/Projects/darling/src/external/python/2.7/Python-2.7.10/Objects/object.c:235
#1  0x00007ffff62a6a2d in _PyLong_New (size=-9223372036854775806) at /home/lubos/Projects/darling/src/external/python/2.7/Python-2.7.10/Objects/longobject.c:76
#2  0x00007ffff62aa429 in PyLong_FromString (str=0x7ffff3138eb9 "L", pend=0x0, base=10) at /home/lubos/Projects/darling/src/external/python/2.7/Python-2.7.10/Objects/longobject.c:1947
#3  0x00007ffff61c07a0 in parsenumber (c=0x7fffffffb120, s=0x7ffff3138eb8 "2L") at /home/lubos/Projects/darling/src/external/python/2.7/Python-2.7.10/Python/ast.c:3341
````

**Comment by LubosD** [comment]
Done, although many OS X extra modules are missing.
