### ISSUE TITLE
Generating stubs based on macOS Monterey/Ventura

### ISSUE THREAD

**Issue by dingari** [darlinghq/darling#1253]
I'm trying to run the stub generator on a MacBook Pro running macOS Ventura.

```
➜  darling-stub-gen /System/Library/Frameworks/CoreGraphics.framework/CoreGraphics CoreGraphis
/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/nm: error: /System/Library/Frameworks/CoreGraphics.framework/CoreGraphics: No such file or directory
Traceback (most recent call last):
  File "/Users/genki/bin/darling-stub-gen", line 130, in <module>
    c_func_out = subprocess.check_output(["nm", "-Ug", full_path])
  File "/Applications/Xcode.app/Contents/Developer/Library/Frameworks/Python3.framework/Versions/3.9/lib/python3.9/subprocess.py", line 424, in check_output
    return run(*popenargs, stdout=PIPE, timeout=timeout, check=True,
  File "/Applications/Xcode.app/Contents/Developer/Library/Frameworks/Python3.framework/Versions/3.9/lib/python3.9/subprocess.py", line 528, in run
    raise CalledProcessError(retcode, process.args,
subprocess.CalledProcessError: Command '['nm', '-Ug', '/System/Library/Frameworks/CoreGraphics.framework/CoreGraphics']' returned non-zero exit status 1.
```

I believe since macOS 12 (Monterey), system framework binaries are no longer located in `/System/Library/Frameworks`. Instead, a shared dyld cache containing binaries for all the frameworks was introduced and is located  in either `/System/Library/dyld/` on Monterey and `/System/Volumes/Preboot/Cryptexes/OS/System/Library/dyld/` on Ventura (as described [here](https://khronokernel.github.io/macos/2022/06/22/VENTURA-DYLD.html)).

The `/System/Library/Frameworks` directory still has the same structure, but the actual framework binaries don't reside there. For example:

```
/System/Library/Frameworks/CoreGraphics.framework/CoreGraphics -> Versions/Current/CoreGraphics
/System/Library/Frameworks/CoreGraphics.framework/Versions/Current -> A

ll /System/Library/Frameworks/CoreGraphics.framework/Versions/A      
total 0
drwxr-xr-x  8 root  wheel   256B Oct 28 08:43 Resources
drwxr-xr-x  3 root  wheel    96B Oct 28 08:43 _CodeSignature
```

The contents of that folder are

```
/System/Library/Frameworks/CoreGraphics.framework/Versions/A/Resources
├── BridgeSupport
│   ├── CoreGraphics.arm64e.bridgesupport
│   ├── CoreGraphics.bridgesupport
│   └── CoreGraphics.dylib
├── CGPSConverterAgent
├── Info.plist
├── ehandler.ps
├── prologue.ps
└── version.plist

2 directories, 8 files
```

Is there a way to use the stub generator on Monterey or Ventura?

**Comment by LubosD** [comment]
Hmm, so they replicated what they did on iOS.

I suppose the easiest way forward would be to extract the cache.

**Comment by dingari** [comment]
Ah, looks like there's a [tool for that](https://github.com/keith/dyld-shared-cache-extractor). I'll poke around and see if I can manage to get somewhere.

**Comment by dingari** [comment]
Well, I managed to extract the libraries, but I run into issues with `class-dump`.

```
class-dump /tmp/libraries/System/Library/Frameworks/CoreGraphics.framework/Versions/A/CoreGraphics
2023-01-05 13:01:18.587 class-dump[65313:864177] Unknown load command: 0x80000033
2023-01-05 13:01:18.622 class-dump[65313:864177] Error: Cannot find offset for address 0x80001dbaf5110 in dataOffsetForAddress:
```

`darling-stub-gen` also had issues with the path not starting with `/System/Libraries/...`, but I was able to work around that. Could `class-dump` be having similar problems?

**Comment by vadd98** [comment]
Hi, is there any news about this? 
I'd like to extract some of the new frameworks introduced with Monterey like ShazamKit.
Is the new darling-stub-gen in the https://github.com/darlinghq/darling/issues/1253#issuecomment-1372256720 enough to extract them?

**Comment by dingari** [comment]
@vadd98 did you try the [dyld-shared-cache-extractor](https://github.com/keith/dyld-shared-cache-extractor) tool?

Turned out I did not have a need for generating stubs automatically, so I haven't given this any thought recently.

**Comment by vadd98** [comment]
I tried and I succedded in exctracting the libraries from the cache, by the way I still need to generate symbols.
Any suggestion?

**Comment by CuriousTommy** [comment]
I looked at the symbols in ShazamKit and they seem to be Objective C symbols, so my program should be able to generate stubs from symbols (in theory).

With that being said, if you just want to see the symbols, you can use the `nm` tools instead.

**Comment by vadd98** [comment]
Thanks @CuriousTommy, using your program of https://github.com/darlinghq/darling/issues/1253?notification_referrer_id=NT_kwDOBEKCv7M1MjQ5NTAzMDcwOjcxNDY3NzEx#issuecomment-1372256720 and [dyld-shared-cache-extractor](https://github.com/keith/dyld-shared-cache-extractor) I succeded in generating the stubs!

**Comment by dingari** [comment]
Great to hear!

BTW, I think this issue can be closed? (@LubosD)
