### ISSUE TITLE
Python: Loaded module does not contain symbol _init[modulename]

### ISSUE THREAD

**Issue by bugaevc** [darlinghq/darling#219]
To reproduce:
```
$ darling shell python
Python 2.7.10 (default, Jan  2 2017, 09:46:13) 
[GCC 4.2.1 Compatible Clang 3.8.0 (tags/RELEASE_380/final)] on darwin
Type "help", "copyright", "credits" or "license" for more information.
>>> import io
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/io.py", line 51, in <module>
    import _io
ImportError: Loaded module does not contain symbol _init_io
>>> 
```

So, it fails at trying to import `_io` (which is needed, for example, for Rudix). Other modules from `src/external/python/2.7/Python-2.7.10/Modules` behave the same.

The responsible piece of code is in `src/external/python/2.7/Python-2.7.10/Python/dynload_next.c`:

```c
PyOS_snprintf(funcname, sizeof(funcname), "_init%.200s", shortname);
// ...snip...
#ifdef USE_DYLD_GLOBAL_NAMESPACE
    if (!NSIsSymbolNameDefined(funcname)) {
        /* UnlinkModule() isn't implemented in current versions, but calling it does no harm */
        /* NSUnLinkModule(newModule, FALSE); removed: causes problems for ObjC code */
        PyErr_Format(PyExc_ImportError,
                         "Loaded module does not contain symbol %.200s",
                         funcname);
        return NULL;
    }
    theSym = NSLookupAndBindSymbol(funcname);
#else
    theSym = NSLookupSymbolInModule(newModule, funcname);
    if ( theSym == NULL ) {
        /* NSUnLinkModule(newModule, FALSE); removed: causes problems for ObjC code */
        PyErr_Format(PyExc_ImportError,
                         "Loaded module does not contain symbol %.200s",
                         funcname);
        return NULL;
    }
#endif
```

So it looks for `_init[modulename]`, while in fact these modules define `init[modulename] `, ex. `init_io` (for `_io`), `init_ctypes` (for `_ctypes`) and `initcmath` (for `cmath`).

**Comment by bugaevc** [comment]
@LubosD the question is - how does it work on macOS?

**Comment by LubosD** [comment]
Ah, the problem is quite simple: in Mach-O, all symbol names are prefixed with an underscore. Special linker-specific symbols have no underscore (e.g. dyld_stub_binder).

It seems dyld-specific APIs (NSLookup* in the code above) expect these prefixed names, unlike the endorsed APIs (dlsym and friends). I'm surprised this hasn't come up before.

**Comment by bugaevc** [comment]
@LubosD Ah, ok. I'm actually surprised how you managed to use Rudix when neither `curl -O https://raw.githubusercontent.com/rudix-mac/rpm/2016.12.13/rudix.py` nor `sudo python rudix.py install rudix` work :wink:

**Comment by LubosD** [comment]
@bugaevc I assume they must've updated Rudix, breaking it on Darling :-(

**Comment by LubosD** [comment]
Now I see the problem is something else. The symbol name is interpreted correctly, but the symbol is being looked up in the wrong module.

```
(gdb) p module->name()
$3 = 0x6b5ac0 "libpython27.so"
(gdb) bt
#0  __darwin_dlsym (handle=0x6ae670, symbol=0x7fffffffc041 "init_io") at /home/lubos/Projects/darling/src/libdyld/dl_public.cpp:222
#1  0x00007ffff7b19ddc in NSLookupSymbolInModule (module=0x6ae670, symbolName=0x7fffffffc041 "init_io") at /home/lubos/Projects/darling/src/libdyld/dl_public.cpp:260
#2  0x00007ffff61ccaeb in _PyImport_GetDynLoadFunc (fqname=0x7ffff2852e00 "_io", shortname=0x7ffff2852e00 "_io", pathname=0x7ffff2886000 "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/lib-dynload64/_io.so", 
    fp=0x7ffff3f36db8 <usual+152>) at /home/lubos/Projects/darling/src/external/python/2.7/Python-2.7.10/Python/dynload_next.c:103
#3  0x00007ffff61e2d35 in _PyImport_LoadDynamicModule (name=0x7ffff2852e00 "_io", pathname=0x7ffff2886000 "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/lib-dynload64/_io.so", fp=0x7ffff3f36db8 <usual+152>)
    at /home/lubos/Projects/darling/src/external/python/2.7/Python-2.7.10/Python/importdl.c:42
```
