### ISSUE TITLE
[gdb-darling] Support running Mach-Os without specifying /bin/mldr

### ISSUE THREAD

**Issue by LubosD** [darlinghq/darling#289]
This is how the subprocess gets executed:

```
#0  __GI_execvp (file=0x7ffefbcffc17 "/bin/bash", argv=0x7ffefbcfd6a0) at execvp.c:26
#1  0x0000555fcaa43d69 in fork_inferior (exec_file_arg=exec_file_arg@entry=0x555fcca99600 "/usr/local/libexec/darling/bin/mldr", allargs=allargs@entry=0x555fccaefd70 "", env=env@entry=0x555fcca8a430, 
    traceme_fun=traceme_fun@entry=0x555fcaa42760 <inf_ptrace_me()>, init_trace_fun=init_trace_fun@entry=0x0, pre_trace_fun=pre_trace_fun@entry=0x0, shell_file_arg=0x0, exec_fun=0x0) at fork-child.c:381
#2  0x0000555fcaa42a17 in inf_ptrace_create_inferior (ops=0x555fcca100b0, exec_file=0x555fcca99600 "/usr/local/libexec/darling/bin/mldr", allargs=0x555fccaefd70 "", env=0x555fcca8a430, from_tty=<optimized out>)
    at inf-ptrace.c:110
#3  0x0000555fcaa47125 in linux_nat_create_inferior (ops=0x555fcca100b0, exec_file=0x555fcca99600 "/usr/local/libexec/darling/bin/mldr", allargs=0x555fccaefd70 "", env=0x555fcca8a430, from_tty=1)
    at linux-nat.c:1120
#4  0x0000555fcaba62e6 in run_command_1 (args=0x555fcca100b0 "\240\335#\314_U", from_tty=1, tbreak_at_main=-861301248) at infcmd.c:612
#5  0x0000555fcaa87495 in cmd_func (cmd=0x555fcca59ff0, args=0x0, from_tty=1) at cli/cli-decode.c:1913
#6  0x0000555fcac4f603 in execute_command (p=<optimized out>, p@entry=0x555fccaefee0 "", from_tty=1) at top.c:674
#7  0x0000555fcab767ac in command_handler (command=0x555fccaefee0 "") at event-top.c:590
#8  0x0000555fcab76a8a in command_line_handler (rl=<optimized out>) at event-top.c:780
#9  0x0000555fcab75dac in gdb_rl_callback_handler (rl=0x555fccaeff30 "\003") at event-top.c:213
#10 0x00007fc1045d9ab3 in rl_callback_read_char () from /lib/x86_64-linux-gnu/libreadline.so.7
#11 0x0000555fcab75cee in gdb_rl_callback_read_char_wrapper_noexcept () at event-top.c:175
```

**Comment by LubosD** [comment]
Obsolete.
