### ISSUE TITLE
Running Google Backup and Sync tool can't find libGL.so.1 (ELF)

### ISSUE THREAD

**Issue by oscarbg** [darlinghq/darling#342]
using otool I get:
Darling [/Volumes/SystemRoot/media/ivan/datosx/progs2]$ otool -L Backup\ and\ Sync.app/Contents/MacOS/Backup\ and\ Sync 
Backup and Sync.app/Contents/MacOS/Backup and Sync:
	/System/Library/Frameworks/Cocoa.framework/Versions/A/Cocoa (compatibility version 1.0.0, current version 20.0.0)
	/usr/lib/libSystem.B.dylib (compatibility version 1.0.0, current version 1197.1.1)
	/usr/lib/libgcc_s.1.dylib (compatibility version 1.0.0, current version 2577.0.0)
	/System/Library/Frameworks/CoreFoundation.framework/Versions/A/CoreFoundation (compatibility version 150.0.0, current version 855.11.0)

running it I get:
 Backup\ and\ Sync.app/Contents/MacOS/Backup\ and\ Sync          
Cannot load libGL.so.1 (ELF): libGL.so.1: cannot open shared object file: No such file or directory
Abort trap: 6 (core dumped)

**Comment by stek29** [comment]
GUI is not supported yet :(

**Comment by bugaevc** [comment]
Yes, GUI apps are not quite supported yet, but we'd still like to know more about this problem. Do you actually have libGL.so.1 on the host? Where is it? Can you check (with `strace`) why the process can't find it?

**Comment by oscarbg** [comment]
yeah I know that and don't report about lots of apps wanting Carbon framework but this error seemed strange as I'm on Ubuntu 17.04 and Nvidia 381.26.13 via ppa driver working.. I have libGL.so.1 everywhere now as I creating symlinks to to /usr/lib/nvidia-381/libGL.so in /usr/lib64 & /usr/lib in addition to existing /usr/lib/x86_64-..../libGL.so.1 also created links to /usr/lib32/nvidia-381/libGL.so  in /usr/lib32 in addition of existing /usr/lib/i386-.../ links.. and even updated sudo ldconfig so don't know much more to do..
will test strace later I'm writing that on Windows..

**Comment by oscarbg** [comment]
well running strace no clue either:
"strace darling shell /Volumes/SystemRoot/media/ivan/datosx/progs2/Backup\ and\ Sync.app/Contents/MacOS/Backup\ and\ Sync"

```
execve("/usr/local/bin/darling", ["darling", "shell", "/Volumes/SystemRoot/media/ivan/d"...], [/* 62 vars */]) = 0
brk(NULL)                               = 0xb91000
fcntl(0, F_GETFD)                       = 0
fcntl(1, F_GETFD)                       = 0
fcntl(2, F_GETFD)                       = 0
access("/etc/suid-debug", F_OK)         = -1 ENOENT (No such file or directory)
access("/etc/ld.so.nohwcap", F_OK)      = -1 ENOENT (No such file or directory)
mmap(NULL, 12288, PROT_READ|PROT_WRITE, MAP_PRIVATE|MAP_ANONYMOUS, -1, 0) = 0x7f6c3cbcb000
access("/etc/ld.so.preload", R_OK)      = -1 ENOENT (No such file or directory)
open("/etc/ld.so.cache", O_RDONLY|O_CLOEXEC) = 3
fstat(3, {st_mode=S_IFREG|0644, st_size=300841, ...}) = 0
mmap(NULL, 300841, PROT_READ, MAP_PRIVATE, 3, 0) = 0x7f6c3cb81000
close(3)                                = 0
access("/etc/ld.so.nohwcap", F_OK)      = -1 ENOENT (No such file or directory)
open("/lib/x86_64-linux-gnu/libutil.so.1", O_RDONLY|O_CLOEXEC) = 3
read(3, "\177ELF\2\1\1\0\0\0\0\0\0\0\0\0\3\0>\0\1\0\0\0@\16\0\0\0\0\0\0"..., 832) = 832
fstat(3, {st_mode=S_IFREG|0644, st_size=10656, ...}) = 0
mmap(NULL, 2105608, PROT_READ|PROT_EXEC, MAP_PRIVATE|MAP_DENYWRITE, 3, 0) = 0x7f6c3c7a6000
mprotect(0x7f6c3c7a8000, 2093056, PROT_NONE) = 0
mmap(0x7f6c3c9a7000, 8192, PROT_READ|PROT_WRITE, MAP_PRIVATE|MAP_FIXED|MAP_DENYWRITE, 3, 0x1000) = 0x7f6c3c9a7000
close(3)                                = 0
access("/etc/ld.so.nohwcap", F_OK)      = -1 ENOENT (No such file or directory)
open("/lib/x86_64-linux-gnu/libc.so.6", O_RDONLY|O_CLOEXEC) = 3
read(3, "\177ELF\2\1\1\3\0\0\0\0\0\0\0\0\3\0>\0\1\0\0\0\20\5\2\0\0\0\0\0"..., 832) = 832
fstat(3, {st_mode=S_IFREG|0755, st_size=1856752, ...}) = 0
mmap(NULL, 3959200, PROT_READ|PROT_EXEC, MAP_PRIVATE|MAP_DENYWRITE, 3, 0) = 0x7f6c3c3df000
mprotect(0x7f6c3c59d000, 2093056, PROT_NONE) = 0
mmap(0x7f6c3c79c000, 24576, PROT_READ|PROT_WRITE, MAP_PRIVATE|MAP_FIXED|MAP_DENYWRITE, 3, 0x1bd000) = 0x7f6c3c79c000
mmap(0x7f6c3c7a2000, 14752, PROT_READ|PROT_WRITE, MAP_PRIVATE|MAP_FIXED|MAP_ANONYMOUS, -1, 0) = 0x7f6c3c7a2000
close(3)                                = 0
mmap(NULL, 8192, PROT_READ|PROT_WRITE, MAP_PRIVATE|MAP_ANONYMOUS, -1, 0) = 0x7f6c3cb7f000
arch_prctl(ARCH_SET_FS, 0x7f6c3cb7f700) = 0
mprotect(0x7f6c3c79c000, 16384, PROT_READ) = 0
mprotect(0x7f6c3c9a7000, 4096, PROT_READ) = 0
mprotect(0x606000, 4096, PROT_READ)     = 0
mprotect(0x7f6c3cbce000, 4096, PROT_READ) = 0
munmap(0x7f6c3cb81000, 300841)          = 0
geteuid()                               = 1001
readlink("/proc/self/exe", "/usr/local/bin/darling", 4095) = 22
write(2, "Sorry, the `/usr/local/bin/darli"..., 83Sorry, the `/usr/local/bin/darling' binary is not setuid root, which is mandatory.
) = 83
write(2, "Darling needs this in order to c"..., 86Darling needs this in order to create mount and PID namespaces and to perform mounts.
) = 86
exit_group(1)                           = ?
+++ exited with 1 +++
```

worried about:
```
write(2, "Sorry, the `/usr/local/bin/darli"..., 83Sorry, the `/usr/local/bin/darling' binary is not setuid root, which is mandatory.
) = 83
write(2, "Darling needs this in order to c"..., 86Darling needs this in order to create mount and PID namespaces and to perform mounts.
```
but
/usr/local/bin$ ls -l darling
-rwsr-xr-x 1 root root 58216 sep  2 10:52 darling

**Comment by bugaevc** [comment]
Well, when you want to `starce` a suid binary, you have to run `strace` itself as root (and use `-u $USER` to let the program know what the original user was). However, in this case, `strace`-ing `darling shell` invocation won't get you anything interesting, because the real shell is spawned from `shellspawn`.

Instead, you should launch `darling shell` as usual, figure out its PID (from outside of the container), and then use something like `sudo strace -f -p THAT_PID` (again, from the outside).

(And we should really start documenting these things...)

**Comment by bugaevc** [comment]
Please retest, this should have been fixed in 81372b97de87c5e22b8a7f4f3fe65b827f744e4c

**Comment by jlucfarias** [comment]
When testing it and add symbols (will push soon) to make it work, it get stuck at this message

```
/Applications/Backup and Sync.app/Contents/Resources/lib/python2.7/site-packages.zip/wx/_core.py:16633: UserWarning: wxPython/wxWidgets release number mismatch
Traceback (most recent call last):
  File "/private/var/netboot/tmp/tmpfs/src/piper/googleclient/apps/webdrive_sync/osx/dist/Backup and Sync.app/Contents/Resources/__boot__.py", line 148, in <module>
  File "/private/var/netboot/tmp/tmpfs/src/piper/googleclient/apps/webdrive_sync/osx/dist/Backup and Sync.app/Contents/Resources/__boot__.py", line 82, in _run
  File "/Applications/Backup and Sync.app/Contents/Resources/main.py", line 8, in <module>
    from osx import run_googledrive
  File "osx/run_googledrive.pyo", line 20, in <module>
  File "common/multi_account/utils.pyo", line 9, in <module>
  File "common/file_utils.pyo", line 14, in <module>
  File "common/client_exceptions.pyo", line 9, in <module>
  File "common/blacklist_notification_types.pyo", line 3, in <module>
  File "/private/var/netboot/tmp/tmpfs/src/piper/googleclient/apps/webdrive_sync/osx/dist/Backup and Sync.app/Contents/Resources/lib/python2.7/resources/i18n/string_resources.py", line 10, in <module>
  File "common/locale_utils.pyo", line 14, in <module>
  File "platforms/__init__.pyo", line 32, in load_module
  File "importlib/__init__.pyo", line 37, in import_module
  File "osx/fileutils.pyo", line 21, in <module>
  File "CoreServices/__init__.pyo", line 14, in <module>
  File "CoreServices/DictionaryServices/__init__.pyo", line 21, in <module>
  File "objc/_lazyimport.pyo", line 86, in __init__
  File "objc/_lazyimport.pyo", line 46, in _loadBundle
ImportError: Bundle could not be loaded
See the Console for a detailed traceback.s occurred, or that you do not have all of the dependencies for this application.
```

## Edit
The dump above is gone, will soon upload the fix
