### ISSUE TITLE
Python 3 wants sysconf(SC_SEM_NSEMS_MAX)

### ISSUE THREAD

**Issue by bugaevc** [darlinghq/darling#692]
```python
Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/compileall.py", line 327, in <module>
    exit_status = int(not main())
  File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/compileall.py", line 309, in main
    if not compile_dir(dest, maxlevels, args.ddir,
  File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/compileall.py", line 85, in compile_dir
    with ProcessPoolExecutor(max_workers=workers) as executor:
  File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/concurrent/futures/process.py", line 511, in __init__
    _check_system_limits()
  File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/concurrent/futures/process.py", line 461, in _check_system_limits
    nsems_max = os.sysconf("SC_SEM_NSEMS_MAX")
FileNotFoundError: [Errno 2] No such file or directory
```

https://github.com/darlinghq/darling/blob/1c13dc74a9e84cce1c46b05733b89927ef59a867/src/libc/gen/FreeBSD/sysconf.c#L313-L321

**Comment by LubosD** [comment]
I'm not sure if this commit I just made helps, but returning -1 should be a valid result (as is on Linux).

**Comment by bugaevc** [comment]
Yep, appears to be fixed
