### ISSUE TITLE
xar silently fails to process InstallESDDmg.pkg

### ISSUE THREAD

**Issue by HinTak** [darlinghq/darling#800]
I suspect it is because it is over 4GB in size. This is just one of Apple's own OS update/installer, supposedly `091-76348-10.13.4`, as far as I can tell. It silently fails, and creates an empty `InstallESD.dmg` . I managed to do it with python binding of libarchive.

(sort of follow-up to https://github.com/darlinghq/darling/issues/782 , trying to extract libfontvalidation from a recent mac os x installer)

The native version of xar on fedora (1.8 apparently more recent than yours), segfaults at - which seems to suggest something related to extracting the resource fork:

```
(gdb) bt
#0  0x0000000000000004 in ?? ()
#1  0x00007ffff7fbabd3 in xar_attrcopy_from_heap (x=0x55555555e2c0, f=0x55555557e8b0, p=0x55555557efc0, wcb=0x7ffff7fb7580 <xar_rsrc_write>, 
    context=0x7fffffffcd00) at lib/io.c:530
#2  0x00007ffff7fb79dc in underbar_extract (x=0x55555555e2c0, f=0x55555557e8b0, file=0x7fffffffbcb0 "./._InstallESD.dmg", 
    context=context@entry=0x7fffffffcd00) at lib/darwinattr.c:654
#3  0x00007ffff7fb7c4d in xar_darwinattr_extract (x=<optimized out>, f=<optimized out>, file=<optimized out>, buffer=<optimized out>, len=<optimized out>)
    at lib/darwinattr.c:776
#4  0x00007ffff7fb6c49 in xar_arcmod_extract (x=x@entry=0x55555555e2c0, f=f@entry=0x55555557e8b0, file=file@entry=0x55555557f560 "InstallESD.dmg", 
    buffer=buffer@entry=0x0, len=len@entry=0) at lib/arcmod.c:97
#5  0x00007ffff7fb50ee in xar_extract_tofile (x=x@entry=0x55555555e2c0, f=f@entry=0x55555557e8b0, path=path@entry=0x55555557f560 "InstallESD.dmg")
    at lib/archive.c:1376
#6  0x00007ffff7fb5369 in xar_extract (x=0x55555555e2c0, f=0x55555557e8b0) at lib/archive.c:1491
#7  0x0000555555557e23 in extract (arglen=<optimized out>, args=<optimized out>, filename=<optimized out>) at src/xar.c:477
#8  main (argc=<optimized out>, argv=<optimized out>) at src/xar.c:1211
(gdb) quit
```

There is a `./._InstallESD.dmg" file created, indeed, so that may or may not be an issue. but `InstallESD.dmg` itself is created empty.

**Comment by HinTak** [comment]
updating to apple's upstream 420 does not fix it either.
