### ISSUE TITLE
Latest Version of Python3 is Not Able To Be Installed

### ISSUE THREAD

**Issue by CuriousTommy** [darlinghq/darling#862]
**Expected Result**
The latest version of Python3 (3.8.5 at the time of writing) should be able to install without issue.

**Actual Result**
```
Darling [~/Downloads]$ installer -pkg python-3.8.5-macosx10.9.pkg -target /
installer: Package name is Python
installer: Installing at base path /
installer: Installing selected choice default
installer: Installing selected choice Python Framework
installer: Installing package org.python.Python.PythonFramework-3.8 version 0 (65057 KB)
installer: Extracting files
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/multiprocessing/spawn.py", line 115, in spawn_main
    parent_sentinel = os.dup(pipe_handle)
OSError: [Errno 22] Invalid argument
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/multiprocessing/spawn.py", line 115, in spawn_main
    parent_sentinel = os.dup(pipe_handle)
OSError: [Errno 22] Invalid argument
Terminated: 15
Darling [~/Downloads]$ python3
bash: python3: command not found
```

**Steps To Reproduce**
1. Download [Python3 3.8.5](https://www.python.org/ftp/python/3.8.5/python-3.8.5-macosx10.9.pkg)
2. Run `installer -pkg python-3.8.5-macosx10.9.pkg -target /`

**System Information**
Fedora 32

| Software | Version |
| --- | --- |
| Linux Kernel | 5.7.14-200.fc32.x86_64 |
| Darling | c03f2b9702c00bda95e580aae01e461cbeb2a0d0 |

**Comment by facekapow** [comment]
This works now on master.
